version: '3.8'

services:
  backend-node:
    build: ./backend-node
    ports:
      - "4000:4000"
    volumes:
      - ./backend-node:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - backend-flask

  backend-flask:
    build: ./backend-flask
    ports:
      - "5001:5000"
    volumes:
      - ./backend-flask:/app
    environment:
      - FLASK_ENV=production